<h1 class="page-header"><?php echo $this->messageFormat(
    $this->translate('suitwalk-headline'),
    [
        'nextDate' => $this->suitwalkOptions()->getNextDate(),
    ]
); ?></h1>

<p>
    <?php echo $this->messageFormat(
        $this->translate('lead-paragraph'),
        [
            'nextDate' => $this->suitwalkOptions()->getNextDate(),
            'furbaseThreadUrl' => $this->suitwalkOptions()->getFurbaseThreadUrl(),
            'telegramGroupUrl' => $this->suitwalkOptions()->getTelegramGroupUrl(),
        ]
    ); ?>
</p>

<h2><?php echo $this->translate('registration'); ?></h2>

<?php if ($this->registrationClosed): ?>
    <p>
        <?php echo $this->translate('registration-closed-hint'); ?>
    </p>
<?php elseif (null !== $this->login()): ?>
<div class="panel panel-default">
    <div class="panel-body">
    <form class="form-inline" method="post" action="<?php echo $this->url('home'); ?>">
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('name')); ?>
            <?php echo $this->formElement($this->form->get('name')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('group')); ?>
            <?php echo $this->formElement($this->form->get('group')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('walkStatus')); ?>
            <?php echo $this->formElement($this->form->get('walkStatus')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('dinnerStatus')); ?>
            <?php echo $this->formElement($this->form->get('dinnerStatus')); ?>
        </div>

        <button type="submit" class="btn btn-success"><?php echo $this->translate('change-registration'); ?></button>
    </form>
    </div>
</div>
<?php else: ?>
    <p>
        <?php echo $this->translate('registration-hint'); ?>
    </p>
<?php endif ?>

<div class="row">
    <div class="col-md-4">
        <h2><?php echo $this->translate('meeting-point'); ?></h2>

        <address>
            <?php echo nl2br($this->escapeHtml($this->suitwalkOptions()->getMeetingPointAddress())); ?>
        </address>

        <iframe
            src="<?php echo $this->suitwalkOptions()->getMeetingPointEmbedUrl(); ?>"
            accesskey=""
            class="map"
            allowfullscreen="allowfullscreen"
        ></iframe>
    </div>
    <div class="col-md-4">
        <h2><?php echo $this->translate('restaurant'); ?></h2>

        <address>
            <?php echo nl2br($this->escapeHtml($this->suitwalkOptions()->getRestaurantAddress())); ?>
        </address>

        <iframe
            src="<?php echo $this->suitwalkOptions()->getRestaurantEmbedUrl(); ?>"
            accesskey=""
            class="map"
            allowfullscreen="allowfullscreen"
        ></iframe>
    </div>
    <div class="col-md-4">
        <h2><?php echo $this->translate('schedule'); ?></h2>

        <ul class="list-unstyled">
            <li><?php echo $this->messageFormat(
                $this->translate('schedule:meeting-time'),
                [
                    'meetingTime' => $this->suitwalkOptions()->getMeetingTime()
                ]
            ); ?>
            (<?php echo $this->suitwalkOptions()->getMeetingPointAdditionalInformation($this->translate('language-code')); ?>)</li>
            <li><?php echo $this->messageFormat(
                $this->translate('schedule:departure-time'),
                [
                    'departureTime' => $this->suitwalkOptions()->getDepartureTime()
                ]
            ); ?></li>
            <li><?php echo $this->messageFormat(
                $this->translate('schedule:return-time'),
                [
                    'returnTime' => $this->suitwalkOptions()->getReturnTime()
                ]
            ); ?></li>
            <li><?php echo $this->messageFormat(
                $this->translate('schedule:dinner-time'),
                [
                    'dinnerTime' => $this->suitwalkOptions()->getDinnerTime()
                ]
            ); ?></li>
        </ul>
    </div>
</div>

<h2><?php echo $this->translate('walk-attendees'); ?></h2>
<div class="row">
    <?php
    $certainDinnerAttendees = [];
    $uncertainDinnerAttendees = [];
    ?>

    <?php foreach ($this->groups as $group): ?>
        <?php
        $groupAttendees = $group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getWalkStatus() !== App\Entity\Attendee::STATUS_NO;
        });

        $certainDinnerAttendees = array_merge($group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getDinnerStatus() === App\Entity\Attendee::STATUS_YES;
        })->toArray(), $certainDinnerAttendees);

        $uncertainDinnerAttendees = array_merge($group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getDinnerStatus() === App\Entity\Attendee::STATUS_MAYBE;
        })->toArray(), $uncertainDinnerAttendees);
        ?>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->translate($group->getName()); ?>
                    <span class="badge"><?php echo count($groupAttendees); ?></span>
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <?php foreach ($groupAttendees as $attendee): ?>
                            <li class="status-<?php echo $attendee->getWalkStatus(); ?>">
                                <?php echo $this->escapeHtml($attendee->getName()); ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<h2><?php echo $this->translate('dinner-attendees'); ?></h2>
<p>
    <?php
    echo $this->messageFormat(
        $this->translate('dinner-attendee-information'),
        [
            'certainDinnerAttendees' => count($certainDinnerAttendees),
            'uncertainDinnerAttendees' => count($uncertainDinnerAttendees),
        ]
    );

    $dinnerAttendees = array_merge($certainDinnerAttendees, $uncertainDinnerAttendees);
    $collator = new Collator('en-US');
    usort($dinnerAttendees, function (App\Entity\Attendee $a, App\Entity\Attendee $b) use ($collator) {
        return $collator->compare($a->getName(), $b->getName());
    });
    ?>

    <ul class="dinner-attendees">
        <?php foreach ($dinnerAttendees as $attendee): ?>
            <li class="status-<?php echo $attendee->getDinnerStatus(); ?>">
                <?php echo $this->escapeHtml($attendee->getName()); ?>
            </li>
        <?php endforeach; ?>
    </ul>
</p>

<h2><?php echo $this->translate('legend'); ?></h2>
<dl class="legend">
    <dt class="certain"><?php echo $this->translate('legend-certain-term'); ?></dt>
    <dd class="certain"><?php echo $this->translate('legend-certain-definition'); ?></dd>

    <dt class="uncertain"><?php echo $this->translate('legend-uncertain-term'); ?></dt>
    <dd class="uncertain"><?php echo $this->translate('legend-uncertain-definition'); ?></dd>
</dl>