<h1 class="page-header">Anmeldung</h1>

<?php if (null !== $this->login()): ?>
    <form class="form-inline" method="post" action="<?php echo $this->url('home'); ?>">
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('name')); ?>
            <?php echo $this->formElement($this->form->get('name')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('group')); ?>
            <?php echo $this->formElement($this->form->get('group')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('walkStatus')); ?>
            <?php echo $this->formElement($this->form->get('walkStatus')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('dinnerStatus')); ?>
            <?php echo $this->formElement($this->form->get('dinnerStatus')); ?>
        </div>

        <button type="submit" class="btn btn-success">Eintrag ändern</button>
    </form>
<?php else: ?>
    <p>
        Um dich für den Suitwalk zu registrieren, melde dich bitte oben mit deiner E-Mail Adresse an. Du erhälst dann
        einen Link per E-Mail, mit dem du dich in die Liste eintragen kannst.
    </p>
<?php endif ?>

<h1 class="page-header">Walk-Teilnehmer</h1>
<div class="row">
    <?php
    $certainDinnerAttendees = 0;
    $uncertainDinnerAttendees = 0;
    ?>

    <?php foreach ($this->groups as $group): ?>
        <?php
        $groupAttendees = $group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getWalkStatus() !== App\Entity\Attendee::STATUS_NO;
        });

        $certainDinnerAttendees += count($group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getDinnerStatus() === App\Entity\Attendee::STATUS_YES;
        }));

        $uncertainDinnerAttendees += count($group->getAttendees()->filter(function (App\Entity\Attendee $attendee) {
            return $attendee->getDinnerStatus() === App\Entity\Attendee::STATUS_MAYBE;
        }));
        ?>
        <div class="col-md-3">
            <h2>
                <?php echo $this->escapeHtml($group->getName()); ?>
                <span class="badge"><?php echo count($groupAttendees); ?></span>
            </h2>
            <ul>
                <?php foreach ($groupAttendees as $attendee): ?>
                    <li>
                        <?php echo $this->escapeHtml($attendee->getName()); ?>
                        <?php if ($attendee->getWalkStatus() === App\Entity\Attendee::STATUS_MAYBE): ?>
                            (?)
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endforeach; ?>
</div>

<h1 class="page-header">Essen-Teilnehmer</h1>
<p>
    <?php echo MessageFormatter::formatMessage(
        'de_DE',
        '
            Es
            {0, plural, =0{hat sich <strong>keine</strong> Person} =1{hat sich <strong>eine</strong> Person} other{haben sich <strong>#</strong> Personen}}
            fest zum Essen eingetragen,
            {1, plural, =0{<strong>keine</strong> Person weiß} =1{<strong>eine</strong> Person weiß} other{<strong>#</strong> Personen wissen}}
            es noch nicht.
        ',
        [$certainDinnerAttendees, $uncertainDinnerAttendees]
    ); ?>
</p>