<?php
/* @var $event Suitwalk\Domain\Event\Event */
/* @var $groups Suitwalk\Domain\Group\Group[] */

/* @var $suitwalkOptions Suitwalk\Infrastructure\Options\SuitwalkOptions */
$suitwalkOptions = $this->getSuitwalkOptions();

/* @var $translator Suitwalk\Infrastructure\I18n\Translator */
$translator = $this->getTranslator($locale);

$this->layout('layout::default', [
    'displayName' => $displayName,
    'translator' => $translator,
]);

$collator = new Collator($locale);
$collator->setAttribute(Collator::ALTERNATE_HANDLING, Collator::SHIFTED);
$collator->setAttribute(Collator::STRENGTH, Collator::QUATERNARY);

$attendeeSort = function (Suitwalk\Domain\Attendee\Attendee $a, Suitwalk\Domain\Attendee\Attendee $b) use ($collator) {
    return $collator->compare($a->getName(), $b->getName());
};
?>

<h1 class="page-header"><?php echo $translator->translate('suitwalk-headline', [
    'nextDate' => $event->getDate(),
]); ?></h1>

<p>
    <?php echo $translator->translate('lead-paragraph', [
        'nextDate' => $event->getDate(),
        'furbaseThreadUrl' => $suitwalkOptions->getFurbaseThreadUrl(),
        'telegramGroupUrl' => $suitwalkOptions->getTelegramGroupUrl(),
    ]); ?>
</p>

<div class="alert alert-info">
    <h4 class="alert-heading"><?php echo $translator->translate('covid-19-heading'); ?></h4>
    <p><?php echo $translator->translate('covid-19-paragraph'); ?></p>
</div>

<h2><?php echo $translator->translate('registration'); ?></h2>

<?php if ($registrationClosed): ?>
    <p>
        <?php echo $translator->translate('registration-closed-hint'); ?>
    </p>
<?php elseif (null !== $form): ?>
    <div class="panel panel-default">
        <div class="panel-body">
        <form class="form-inline" method="post" action="<?php echo $this->url('home'); ?>" id="attendee-form">
            <?php
            $inputHelper = new DASPRiD\Formidable\Helper\InputText();
            $selectHelper = new DASPRiD\Formidable\Helper\Select();

            $groupMap = [];

            foreach ($groups as $group) {
                $groupMap[$group->getId()] = $group->getName($translator->translate('language-code'));
            }

            $statusMap = [
                Suitwalk\Domain\Attendee\Attendee::STATUS_YES => $translator->translate('yes'),
                Suitwalk\Domain\Attendee\Attendee::STATUS_MAYBE => $translator->translate('maybe'),
                Suitwalk\Domain\Attendee\Attendee::STATUS_NO => $translator->translate('no'),
            ];
            ?>

            <?php foreach ($form->getField('attendees')->getIndexes() as $index): ?>
                <fieldset>
                    <div class="form-group">
                        <label><?php echo $translator->translate('name'); ?></label>
                        <?php echo $inputHelper($form->getField(sprintf('attendees[%d][name]', $index)), [
                            'class' => 'form-control',
                            'required' => 'required',
                            'maxlength' => '32',
                        ]); ?>
                    </div>
                    <div class="form-group">
                        <label><?php echo $translator->translate('group'); ?></label>
                        <?php echo $selectHelper($form->getField(sprintf('attendees[%d][group]', $index)), $groupMap, [
                            'class' => 'form-control',
                            'required' => 'required',
                        ]); ?>
                    </div>
                    <div class="form-group">
                        <label><?php echo $translator->translate('walk'); ?></label>
                        <?php echo $selectHelper($form->getField(sprintf('attendees[%d][walkStatus]', $index)), $statusMap, [
                            'class' => 'form-control',
                            'required' => 'required',
                        ]); ?>
                    </div>
                    <div class="form-group">
                        <label><?php echo $translator->translate('dinner'); ?></label>
                        <?php echo $selectHelper($form->getField(sprintf('attendees[%d][dinnerStatus]', $index)), $statusMap, [
                            'class' => 'form-control',
                            'required' => 'required',
                        ]); ?>
                    </div>

                    <a href="#" class="btn btn-danger remove-attendee"><span class="glyphicon glyphicon-remove"></span></a>
                </fieldset>
            <?php endforeach; ?>

            <button type="submit" class="btn btn-success"><?php echo $translator->translate('change-registration'); ?></button>
            <a class="btn btn-primary add-attendee" href="#"><?php echo $translator->translate('add-attendee'); ?></a>
        </form>
        </div>
    </div>
<?php else: ?>
    <p>
        <?php echo $translator->translate('registration-hint'); ?>
    </p>
<?php endif ?>

<div class="row">
    <div class="col-md-4">
        <h2><?php echo $translator->translate('meeting-point'); ?></h2>

        <address>
            <?php echo nl2br($this->escape($event->getMeetingPointAddress())); ?>
        </address>

        <iframe
            src="https://www.google.com/maps/embed/v1/place?key=<?php echo $suitwalkOptions->getMapsApiKey(); ?>&amp;q=<?php echo urlencode(str_replace("\n", ',', $event->getMeetingPointAddress())); ?>"
            accesskey=""
            class="map"
            allowfullscreen="allowfullscreen"
        ></iframe>
    </div>
    <div class="col-md-4">
        <h2><?php echo $translator->translate('restaurant'); ?></h2>

        <address>
            <?php echo nl2br($this->escape($event->getRestaurantAddress())); ?>
        </address>

        <iframe
            src="https://www.google.com/maps/embed/v1/place?key=<?php echo $suitwalkOptions->getMapsApiKey(); ?>&amp;q=<?php echo urlencode(str_replace("\n", ',', $event->getRestaurantAddress())); ?>"
            accesskey=""
            class="map"
            allowfullscreen="allowfullscreen"
        ></iframe>
    </div>
    <div class="col-md-4">
        <h2><?php echo $translator->translate('schedule'); ?></h2>

        <ul class="list-unstyled">
            <li><?php echo $translator->translate('schedule:meeting-time', [
                'meetingTime' => $event->getMeetingTime()
            ]); ?>
            (<?php echo $event->getMeetingPointExtra($translator->translate('language-code')); ?>)</li>
            <li><?php echo $translator->translate('schedule:departure-time', [
                'departureTime' => $event->getDepartureTime()
            ]); ?></li>
            <li><?php echo $translator->translate('schedule:return-time', [
                'returnTime' => $event->getReturnTime()
            ]); ?></li>
            <li><?php echo $translator->translate('schedule:dinner-time', [
                'dinnerTime' => $event->getDinnerTime()
            ]); ?></li>
        </ul>
    </div>
</div>

<?php
$attendees = $event->getAttendees();
?>

<h2>
    <?php echo $translator->translate('walk-attendees'); ?>
    <span class="badge">
        <?php
        echo count(array_filter($attendees, function (\Suitwalk\Domain\Attendee\Attendee $attendee) : bool {
            return $attendee->getWalkStatus() !== Suitwalk\Domain\Attendee\Attendee::STATUS_NO;
        }));
        ?>
    </span>
</h2>
<div class="row">
    <?php
    ?>

    <?php foreach ($groups as $group): ?>
        <?php
        $groupAttendees = array_filter($attendees, function (Suitwalk\Domain\Attendee\Attendee $attendee) use ($group) {
            if ($attendee->getGroup() !== $group) {
                return false;
            }

            return $attendee->getWalkStatus() !== Suitwalk\Domain\Attendee\Attendee::STATUS_NO;
        });
        usort($groupAttendees, $attendeeSort);
        ?>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $group->getName($translator->translate('language-code')); ?>
                    <span class="badge"><?php echo count($groupAttendees); ?></span>
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <?php foreach ($groupAttendees as $attendee): ?>
                            <li class="status-<?php echo $attendee->getWalkStatus(); ?>">
                                <?php echo $this->escape($attendee->getName()); ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<h2>
    <?php echo $translator->translate('dinner-attendees'); ?>
    <span class="badge">
        <?php
        echo count(array_filter($attendees, function (\Suitwalk\Domain\Attendee\Attendee $attendee) : bool {
            return $attendee->getDinnerStatus() !== Suitwalk\Domain\Attendee\Attendee::STATUS_NO;
        }));
        ?>
    </span>
</h2>
<p>
    <?php
    $certainDinnerAttendees = [];
    $uncertainDinnerAttendees = [];
    $certainDinnerAttendees = array_filter($attendees, function (Suitwalk\Domain\Attendee\Attendee $attendee) {
        return $attendee->getDinnerStatus() === Suitwalk\Domain\Attendee\Attendee::STATUS_YES;
    });

    $uncertainDinnerAttendees = array_filter($attendees, function (Suitwalk\Domain\Attendee\Attendee $attendee) {
        return $attendee->getDinnerStatus() === Suitwalk\Domain\Attendee\Attendee::STATUS_MAYBE;
    });

    echo MessageFormatter::formatMessage(
        $locale,
        $translator->translate('dinner-attendee-information'),
        [
            'certainDinnerAttendees' => count($certainDinnerAttendees),
            'uncertainDinnerAttendees' => count($uncertainDinnerAttendees),
        ]
    );

    $dinnerAttendees = array_merge($certainDinnerAttendees, $uncertainDinnerAttendees);
    $collator = new Collator($locale);
    usort($dinnerAttendees, $attendeeSort);
    ?>

    <ul class="dinner-attendees">
        <?php foreach ($dinnerAttendees as $attendee): ?>
            <li class="status-<?php echo $attendee->getDinnerStatus(); ?>">
                <?php echo $this->escape($attendee->getName()); ?>
            </li>
        <?php endforeach; ?>
    </ul>
</p>

<h2><?php echo $translator->translate('legend'); ?></h2>
<dl class="legend">
    <dt class="certain"><?php echo $translator->translate('legend-certain-term'); ?></dt>
    <dd class="certain"><?php echo $translator->translate('legend-certain-definition'); ?></dd>

    <dt class="uncertain"><?php echo $translator->translate('legend-uncertain-term'); ?></dt>
    <dd class="uncertain"><?php echo $translator->translate('legend-uncertain-definition'); ?></dd>
</dl>
