<?php
/* @var $locale string */
/* @var $media Suitwalk\Domain\Medium\Medium[] */

/* @var $translator Suitwalk\Infrastructure\I18n\Translator */
$translator = $this->getTranslator($locale);

$dateFormatter = new IntlDateFormatter($locale, IntlDateFormatter::LONG, IntlDateFormatter::NONE);

$this->layout('layout::default', [
    'displayName' => $displayName,
    'translator' => $translator,
]);
?>

<h1 class="page-header"><?php echo $translator->translate('media'); ?></h1>

<?php
$mediaGroups = [];

foreach ($media as $medium) {
    $dateKey = $medium->getEvent()->getDate()->format('Y-m-d');

    if (!array_key_exists($dateKey, $mediaGroups)) {
        $mediaGroups[$dateKey] = [
            'date' => DateTime::createFromFormat('Y-m-d', $medium->getEvent()->getDate()->format('Y-m-d')),
            'types' => [
                Suitwalk\Domain\Medium\Medium::TYPE_GALLERY => [],
                Suitwalk\Domain\Medium\Medium::TYPE_VIDEO => [],
            ],
        ];
    }

    $mediaGroups[$dateKey]['types'][$medium->getType()][] = $medium;
}

$types = [
    Suitwalk\Domain\Medium\Medium::TYPE_GALLERY => $translator->translate('galleries'),
    Suitwalk\Domain\Medium\Medium::TYPE_VIDEO => $translator->translate('videos'),
];

krsort($mediaGroups);
?>

<?php foreach ($mediaGroups as $mediaGroup): ?>
    <div class="panel panel-default media">
        <div class="panel-heading"><?php echo $dateFormatter->format($mediaGroup['date']); ?></div>
        <div class="panel-body">
            <ul>
                <?php foreach ($types as $type => $label): ?>
                    <?php
                    if (empty($mediaGroup['types'][$type])) {
                        continue;
                    }
                    ?>

                    <li>
                        <strong><?php echo $this->escape($label); ?></strong>
                        <ul>
                            <?php foreach ($mediaGroup['types'][$type] as $medium): ?>
                                <li>
                                    <a href="<?php echo $this->escape($medium->getUrl()); ?>">
                                        <?php echo $this->escape($medium->getName()); ?>
                                        (<?php echo $this->escape(parse_url($medium->getUrl(), PHP_URL_HOST)); ?>)
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endforeach; ?>
