<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?php ob_start(); ?>
<?php $y = 20; ?>
<?php $translator = $this->getTranslator($locale); ?>

<?php foreach ($groups as $group): ?>
    <?php
    $attendees = $event->getAttendees();
    $groupAttendees = array_filter($attendees, function (Suitwalk\Domain\Attendee\Attendee $attendee)  use ($group) {
        if ($attendee->getGroup() !== $group) {
            return false;
        }

        return $attendee->getWalkStatus() !== Suitwalk\Domain\Attendee\Attendee::STATUS_NO;
    });
    ?>
    <text x="0" y="<?php echo $y; ?>"  font-size="12" font-weight="bold" font-family="sans-serif" fill="#371a01"><?php echo $group->getName($translator->translate('language-code')); ?></text>

    <?php foreach ($groupAttendees as $attendee): ?>
        <?php $y += 16; ?>
        <text x="0" y="<?php echo $y; ?>" font-size="12"  font-family="sans-serif" fill="#371a01">
            <?php echo $this->escape($attendee->getName()); ?>
            <?php if ($attendee->getWalkStatus() === Suitwalk\Domain\Attendee\Attendee::STATUS_MAYBE): ?>
                (?)
            <?php endif; ?>
        </text>
    <?php endforeach; ?>

    <?php $y += 32; ?>
<?php endforeach; ?>

<?php $contents = ob_get_clean(); ?>

<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="600" height="<?php echo $y; ?>">
    <?php echo $contents; ?>
</svg>
