<?php
$this->headLink()
    ->prependStylesheet('/css/screen.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.2.3.min.js');
?>
<!DOCTYPE html>
<html lang="<?php echo $this->translate('language-code'); ?>">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle('Karlsfurs Suitwalk')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#a98b49">
    <meta name="apple-mobile-web-app-title" content="Karlsfurs Suitwalk">
    <meta name="application-name" content="Karlsfurs Suitwalk">
    <meta name="msapplication-TileColor" content="#6089ab">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->suitwalkOptions()->getFurbaseThreadUrl(); ?>"><?php echo $this->translate('furbase-thread'); ?></a></li>
                    <li><a href="<?php echo $this->suitwalkOptions()->getTelegramGroupUrl(); ?>"><?php echo $this->translate('telegram-group'); ?></a></li>
                </ul>

                <?php $emailAddress = $this->login(); ?>
                <?php if (null === $emailAddress): ?>
                    <form class="navbar-form navbar-right" method="POST" action="<?php echo $this->url('login'); ?>">
                        <div class="form-group">
                            <input type="email" name="emailAddress" placeholder="<?php echo $this->translate('email-address'); ?>" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success"><?php echo $this->translate('login'); ?></button>
                    </form>
                <?php else: ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <p class="navbar-text">
                                <?php echo $this->messageFormat($this->translate('logged-in-as'), ['emailAddress' => $this->escapeHtml($emailAddress)]); ?>
                            </p>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('logout'); ?></a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </nav>

        <header id="header">
            <ul class="language-selection">
                <li class="german<?php if ('de' === $this->translate('language-code')): ?> active<?php endif; ?>"><a href="<?php echo $this->url('language', ['locale' => 'de-DE']); ?>">Deutsch</a></li>
                <li class="english<?php if ('en' === $this->translate('language-code')): ?> active<?php endif; ?>"><a href="<?php echo $this->url('language', ['locale' => 'en-US']); ?>">English</a></li>
            </ul>
        </header>

        <div id="content">
            <?php echo $this->content ?>
        </div>

        <footer id="footer">
            <p>
                Copyright 2016 Ben 'DASPRiD' Scholzen |
                <a href="https://github.com/DASPRiD/karlsfurs-registration">GitHub</a>
            </p>
        </footer>
    </div>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
